### ISSUE TITLE
[Admin][Composter] Permettre la modification d'un composteur uniquement pour les administrateurs

### ISSUE THREAD

**Issue by EwennV** [EwennV/CompostMe#27]
Il faut prendre en compte que le formulaire de création est adapté pour la modification, il suffit de passer l'objet en deuxième argument dans la méthode buildForm.

Script JS à modifier pour n'afficher que le composteur en cours de modification et pouvoir déplacer le curseur en conséquence.

**Comment by xenS14** [comment]
Changer de place la page pour ajouter un composteur, déplacer ça dans le panel admin
